version: '2.1'

services:
  telegraf-snmp:
    image: telegraf-snmp
    build: .
    ports:
      - 8125:8125
      - 8092:8092
      - 8094:8094
    volumes:
      - c:\dockerdev\apps\telegraf-snmp\telegraf.conf:/etc/telegraf/telegraf.conf
